(source melpa)

(depends-on "ace-jump-mode")
(depends-on "aggressive-indent")
(depends-on "chruby")
(depends-on "enh-ruby-mode")
(depends-on "exec-path-from-shell")
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "inf-ruby")
(depends-on "magit")
(depends-on "pallet")
(depends-on "rspec-mode")
(depends-on "smartparens")
(depends-on "undo-tree")